name: HTMLKit CI

on: [push]

jobs:
  macOS:
    name: Test macOS 
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1   
        with:
          submodules: recursive  
      - name: macOS
        run: xcodebuild -workspace "ObjectiveRocks.xcworkspace" -scheme "ObjectiveRocks" -destination "platform=macOS" clean test
  pod_lint:
    name: Pod Lint
    runs-on: macOS-latest
    needs: [macOS]
    steps:
      - name: lint
        run: pod lib lint --skip-import-validation --allow-warnings
